import '../styles/flash-cards-table.scss';

function FlashCardsTable() {
  return (
    <table className='flash-cards-table l'>
      <thead>
        <tr>
          <th>Word</th>
          <th>Translation</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Hello</td>
          <td>oi</td>
          <td>Actions</td>
        </tr>
      </tbody>
    </table>
  );
}

export default FlashCardsTable;
